### ISSUE TITLE
webshell url must be FQDN and not an IP

### ISSUE THREAD

**Issue by aa-ux** [c0delatte/carina#1]
Hi,

while trying to load webshell in format http://192.168.1.1/boo/boo.php there is an exception

but when loaded using http://booo.com/boo/boo.php it worked...

**Comment by abaykan** [comment]
Hello, I tried to do as you did, but I didn't get the error you meant. Can you explain more?
![Screenshot](https://assets.codelatte.net/Screenshotfrom2020-06-0309-07-33.png)
